#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', false);
defined('YII_ENV') or define('YII_ENV', 'prod');

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');
require(__DIR__ . '/common/config/bootstrap.php');
require(__DIR__ . '/console/config/bootstrap.php');

$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/common/config/main.php'),
    require(__DIR__ . '/common/config/main-local.php'),
    require(__DIR__ . '/console/config/main.php'),
    require(__DIR__ . '/console/config/main-local.php')
);
//Brian3t: unset common controllermap so that console app can run, otherwise there will be this error:
// PHP Fatal error:  Call to undefined method common\controllers\ProfileController::getHelpSummary() in /var/www/sayygo/vendor/yiisoft/yii2/console/controllers/HelpController.php on line 96
unset($config['modules']['user']['controllerMap']);

$application = new yii\console\Application($config);
//since console does not have baseUrl, get this from common/main-local
Yii::$app->urlManager->setBaseUrl($config['aliases']['absoluteBaseUrl']);

$exitCode = $application->run();
exit($exitCode);
